# Generated by Django 5.2.5 on 2025-09-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_message',
            new_name='customer_message_id',
        ),
    ]
